apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: gke-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "app": "your-app"
  duration: "60s"
  scheduler:
    cron: "@every 4h"   # For scheduled Game Days
