name: Terraform Validate & Plan

on:
  push:
    branches: [ main ]
    paths:
      - 'reference-implementations/terraform-baseline/**'
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./reference-implementations/terraform-baseline/environments/sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.x"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        continue-on-error: true   # Don't fail PR just for plan
