name: Terraform Validate

on:
  push:
    branches: [ main ]
    paths:
      - 'reference-implementations/terraform-baseline/**'
      - 'reference-implementations/slo-monitoring/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]

    defaults:
      run:
        working-directory: ./reference-implementations/terraform-baseline/environments/${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.x"

      - run: terraform init -backend=false
      - run: terraform validate
      - run: terraform fmt -check
